name: Publish to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

  - name: Install oboe
    run: |
      python -m pip install --upgrade pip
      pip install git+https://github.com/kmaasrud/oboe.git

  - name: Generate HTML through oboe
    run: oboe ./vault -o ./out -t ./template.html -d daily

  - name: Publish
    uses: s0/git-publish-subdir-action@develop
    env:
      REPO: self
      BRANCH: gh-pages
      FOLDER: out
<<<<<<< HEAD
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> a5c7c0136ba5d50765196ae8ae7bfcfb28609c21
